### ISSUE TITLE
readerのポジションがおかしくなる？

### ISSUE THREAD

**Issue by kasamal** [nkgami/TTCFileSplitter#1]
ttfTableで "name"タグを見つけたあと、readerのポジションが狂いませんか？
（OpenTypeの仕様をよく理解してないので間違いであればすみません・・・）

**Comment by nkgami** [comment]
@kasamal Thank you for your feedback. I fixed that problem at https://github.com/nkgami/TTCFileSplitter/commit/69eaef8d24dc437faa6f17051bbb0b289de41b54

**Comment by nkgami** [comment]
https://github.com/nkgami/TTCFileSplitter/commit/69eaef8d24dc437faa6f17051bbb0b289de41b54
